In [1]:
import pandas as pd
from transform import *

In [2]:
processed_data = pd.read_csv(r'C:\Users\ulasz\OneDrive\Pulpit\studia\sem6\hurtownie danych\spotify-dwh\etl\output\raw_charts_viral50_20250604_213838.csv')
processed_data

,track_name,rank,date,artist_name,region,chart_type,position_change,weeks_on_chart,peak_position,previous_rank,source_type,track_id,duration,explicit,artist_id,genres,artist_count,release_date,country,type
0,#BrooklynBloodPop!,7,2021-05-17,SyKo,Argentina,viral50,SAME_POSITION,9,5,NaN,charts_viral50,5tDbyeaCvxjNCBcupQucGo,145.612,True,08ZqXO40nMrhBoGma4kls2,"[""hyperpop""]",1.0,2020-07-27,Seattle,Person
1,#BrooklynBloodPop!,5,2021-05-24,SyKo,Argentina,viral50,MOVE_UP,9,5,7.0,charts_viral50,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person
2,#BrooklynBloodPop!,11,2021-05-31,SyKo,Argentina,viral50,MOVE_DOWN,9,5,5.0,charts_viral50,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person
3,#BrooklynBloodPop!,13,2021-06-07,SyKo,Argentina,viral50,MOVE_DOWN,9,5,11.0,charts_viral50,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person
4,#BrooklynBloodPop!,16,2021-06-14,SyKo,Argentina,viral50,MOVE_DOWN,9,5,13.0,charts_viral50,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person
5,#BrooklynBloodPop!,18,2021-06-21,SyKo,Argentina,viral50,MOVE_DOWN,9,5,16.0,charts_viral50,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person
6,#BrooklynBloodPop!,39,2021-06-28,SyKo,Argentina,viral50,MOVE_DOWN,9,5,18.0,charts_viral50,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person
7,#BrooklynBloodPop!,36,2021-07-05,SyKo,Argentina,viral50,MOVE_DOWN,9,5,39.0,charts_viral50,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person
8,#BrooklynBloodPop!,46,2021-07-12,SyKo,Argentina,viral50,MOVE_DOWN,9,5,36.0,charts_viral50,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person
9,#Natural,22,2018-01-08,Paty Cantú,Argentina,viral50,SAME_POSITION,3,12,NaN,charts_viral50,3y7XIu4NloDcCSekDbCvf6,227.266,False,7K9rdoOJSiKXoVXPlSkGKT,"[""latin pop""]",2.0,2018-05-25,Mexico,Person
10,#Natural,12,2018-01-15,"Paty Cantú, Juhn",Argentina,viral50,SAME_POSITION,3,12,22.0,charts_viral50,3y7XIu4NloDcCSekDbCvf6,NaN,NaN,7K9rdoOJSiKXoVXPlSkGKT,NaN,NaN,NaN,Mexico,Person
11,#Natural,27,2018-01-22,"Paty Cantú, Juhn",Argentina,viral50,MOVE_DOWN,3,12,12.0,charts_viral50,3y7XIu4NloDcCSekDbCvf6,NaN,NaN,7K9rdoOJSiKXoVXPlSkGKT,NaN,NaN,NaN,Mexico,Person
12,#WIPEITDOWN (TikTok Classics Version),43,2020-06-08,BMW Kenny,Argentina,viral50,NEW_ENTRY,1,43,NaN,charts_viral50,5qOE3kEU14vcc6OUDkgKkv,135.317,False,5iB9AOsC0IyhPYES06AYo0,[],2.0,2022-08-12,NaN,Person
13,#Ysya2020 Vol. 1 - Una de Dos,32,2020-07-13,YSY A,Argentina,viral50,NEW_ENTRY,1,32,NaN,charts_viral50,7nFta4LZyL0MTDDqbjiQW2,116.599,False,2qWK8K2Jfh67UqtwY8tCW6,"[""argentine trap"", ""trap""]",2.0,2020-06-22,Argentina,Person
14,#Ysya2020 Vol. 4 - Pasa Que Yo,28,2020-11-02,YSY A,Argentina,viral50,NEW_ENTRY,1,28,NaN,charts_viral50,7qf15ZBTnAyOZX5UIWrsKj,100.365,False,2qWK8K2Jfh67UqtwY8tCW6,"[""argentine trap"", ""trap""]",2.0,2020-10-11,Argentina,Person
15,#Ysya2020 Vol. 5 - Silbando,43,2020-11-16,YSY A,Argentina,viral50,NEW_ENTRY,1,43,NaN,charts_viral50,6TI490muJ6RgFsYJc626BZ,119.438,False,2qWK8K2Jfh67UqtwY8tCW6,"[""argentine trap"", ""trap""]",2.0,2020-10-18,Argentina,Person
16,#Ysya2020 Vol. 6 - Un Flow de Infarto,22,2020-11-16,YSY A,Argentina,viral50,NEW_ENTRY,1,22,NaN,charts_viral50,2byu6eeLWaBq88ZtusqU4V,142.376,False,2qWK8K2Jfh67UqtwY8tCW6,"[""argentine trap"", ""trap""]",2.0,2020-10-26,Argentina,Person
17,Good Thing,42,2018-05-07,i-dle,Argentina,viral50,NEW_ENTRY,1,42,NaN,charts_viral50,6d8DgvFxp6lbdfOw9BVkLS,154.386,False,2AfmfGFbe0A0WsTYm0SDTx,"[""k-pop""]",1.0,2025-05-19,South Korea,Group
18,(It Happens) Sometimes,25,2018-09-24,Jack Back,Argentina,viral50,NEW_ENTRY,1,25,NaN,charts_viral50,4psxV3oAIDBXKL2oS9KcFq,202.276,False,4bXUaTjc7TQTvLqqCAlfYt,"[""tech house""]",1.0,2018-08-31,United States,Person
19,(You Make Me Feel Like) A Natural Woman,31,2018-08-20,Aretha Franklin,Argentina,viral50,MOVE_UP,1,31,NaN,charts_viral50,5K09WxKdlkroDyEVyOSySy,165.333,False,7nwUJBm0HE4ZxD3f5cy5ok,"[""soul"", ""motown"", ""classic soul"", ""jazz blues""]",1.0,1968-01-22,United States,Person
20,(no me despegues tu boca),49,2020-04-27,Covi Quintana,Argentina,viral50,NEW_ENTRY,1,49,NaN,charts_viral50,2j0KnNhlO9lY1EWPOkblK3,220.840,False,2sSqkk6j5gRa7MzeQqMfIN,[],1.0,2021-05-21,NaN,Person
21,+ (MÁS),25,2020-01-13,Aitana,Argentina,viral50,NEW_ENTRY,7,25,NaN,charts_viral50,1MXzojJav1N4cREWTFm1iZ,219.354,False,7eLcDZDYHXZCebtQmVFL25,[],2.0,2020-12-10,Spain,Person
22,+,25,2020-01-20,"Aitana, Cali Y El Dandee",Argentina,viral50,MOVE_UP,7,25,25.0,charts_viral50,1MXzojJav1N4cREWTFm1iZ,NaN,NaN,7eLcDZDYHXZCebtQmVFL25,NaN,NaN,NaN,Spain,Person
23,+,44,2020-01-27,"Aitana, Cali Y El Dandee",Argentina,viral50,MOVE_DOWN,7,25,25.0,charts_viral50,1MXzojJav1N4cREWTFm1iZ,NaN,NaN,7eLcDZDYHXZCebtQmVFL25,NaN,NaN,NaN,Spain,Person
24,+,46,2020-02-17,"Aitana, Cali Y El Dandee",Argentina,viral50,NEW_ENTRY,7,25,44.0,charts_viral50,1MXzojJav1N4cREWTFm1iZ,NaN,NaN,7eLcDZDYHXZCebtQmVFL25,NaN,NaN,NaN,Spain,Person
25,+,42,2020-02-24,"Aitana, Cali Y El Dandee",Argentina,viral50,MOVE_DOWN,7,25,46.0,charts_viral50,1MXzojJav1N4cREWTFm1iZ,NaN,NaN,7eLcDZDYHXZCebtQmVFL25,NaN,NaN,NaN,Spain,Person
26,+,50,2020-03-02,"Aitana, Cali Y El Dandee",Argentina,viral50,MOVE_DOWN,7,25,42.0,charts_viral50,1MXzojJav1N4cREWTFm1iZ,NaN,NaN,7eLcDZDYHXZCebtQmVFL25,NaN,NaN,NaN,Spain,Person
27,+,49,2020-03-09,"Aitana, Cali Y El Dandee",Argentina,viral50,SAME_POSITION,7,25,50.0,charts_viral50,1MXzojJav1N4cREWTFm1iZ,NaN,NaN,7eLcDZDYHXZCebtQmVFL25,NaN,NaN,NaN,Spain,Person
28,...Ready For It?,1,2017-09-04,Taylor Swift,Argentina,viral50,NEW_ENTRY,2,1,NaN,charts_viral50,2yLa0QULdQr0qAIvVwN6B5,208.186,False,06HL4z0CvFAxyc27GXpf02,[],1.0,2017-11-10,United States,Person
29,...Ready For It?,10,2017-09-11,Taylor Swift,Argentina,viral50,MOVE_DOWN,2,1,1.0,charts_viral50,2yLa0QULdQr0qAIvVwN6B5,NaN,NaN,06HL4z0CvFAxyc27GXpf02,NaN,NaN,NaN,United States,Person
30,"0 Sentimientos (Remix) [feat. Baby Rasta, Dark...",7,2017-01-02,Boy Wonder CF,Argentina,viral50,MOVE_UP,1,7,NaN,charts_viral50,3gYco8uoFBmpxqYlz3Zhs7,335.736,False,01nUdqwuIHCHLZNP2TvYVF,"[""reggaeton"", ""trap latino""]",8.0,2023-11-21,NaN,NaN
31,0303456 - 1999 vrs,36,2021-07-12,Raffaella Carrà,Argentina,viral50,MOVE_DOWN,1,36,NaN,charts_viral50,1TtHlaxGzDhyF2GyX8dqWV,199.920,False,6EVyI0S0b1Ld2nm37m5x85,[],1.0,1999-10-29,Italy,Person
32,06:00AM CHILDREN OF THE SUN,49,2018-07-09,SACRE,Argentina,viral50,NEW_ENTRY,1,49,NaN,charts_viral50,5BLWG0gtrci22tCyPu2bsP,225.693,False,68nJ4J8L6X6HZNTuZ9e7yT,"[""nu disco""]",1.0,2020-07-10,NaN,Person
33,0X1=LOVESONG (I Know I Love You) feat. Seori,27,2021-06-28,TOMORROW X TOGETHER,Argentina,viral50,SAME_POSITION,1,27,NaN,charts_viral50,1Z8TPHiKeCUyClxV6WTTIf,202.203,False,0ghlgldX5Dd6720Q3qFyQB,"[""k-pop""]",2.0,2021-05-31,South Korea,Group
34,0X1=LOVESONG (I Know I Love You) feat. Seori,26,2021-06-21,TOMORROW X TOGETHER,Argentina,viral50,NEW_ENTRY,1,26,NaN,charts_viral50,1Z8TPHiKeCUyClxV6WTTIf,202.203,False,0ghlgldX5Dd6720Q3qFyQB,"[""k-pop""]",2.0,2021-05-31,South Korea,Group
35,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",3,2018-02-19,Sofía Reyes,Argentina,viral50,NEW_ENTRY,11,1,NaN,charts_viral50,4QtiVmuA88tPQiCOHZuQ5b,201.526,False,0haZhu4fFKt0Ag94kZDiz2,"[""latin pop""]",3.0,2018-02-16,Mexico,Person
36,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",1,2018-02-26,Sofía Reyes,Argentina,viral50,SAME_POSITION,11,1,3.0,charts_viral50,4QtiVmuA88tPQiCOHZuQ5b,NaN,NaN,0haZhu4fFKt0Ag94kZDiz2,NaN,NaN,NaN,Mexico,Person
37,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",9,2018-03-05,Sofía Reyes,Argentina,viral50,MOVE_DOWN,11,1,1.0,charts_viral50,4QtiVmuA88tPQiCOHZuQ5b,NaN,NaN,0haZhu4fFKt0Ag94kZDiz2,NaN,NaN,NaN,Mexico,Person
38,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",15,2018-03-12,Sofía Reyes,Argentina,viral50,MOVE_UP,11,1,9.0,charts_viral50,4QtiVmuA88tPQiCOHZuQ5b,NaN,NaN,0haZhu4fFKt0Ag94kZDiz2,NaN,NaN,NaN,Mexico,Person
39,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",16,2018-03-19,Sofía Reyes,Argentina,viral50,MOVE_DOWN,11,1,15.0,charts_viral50,4QtiVmuA88tPQiCOHZuQ5b,NaN,NaN,0haZhu4fFKt0Ag94kZDiz2,NaN,NaN,NaN,Mexico,Person
40,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",16,2018-03-26,Sofía Reyes,Argentina,viral50,MOVE_DOWN,11,1,16.0,charts_viral50,4QtiVmuA88tPQiCOHZuQ5b,NaN,NaN,0haZhu4fFKt0Ag94kZDiz2,NaN,NaN,NaN,Mexico,Person
41,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",10,2018-04-02,Sofía Reyes,Argentina,viral50,SAME_POSITION,11,1,16.0,charts_viral50,4QtiVmuA88tPQiCOHZuQ5b,NaN,NaN,0haZhu4fFKt0Ag94kZDiz2,NaN,NaN,NaN,Mexico,Person
42,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",17,2018-04-09,Sofía Reyes,Argentina,viral50,MOVE_DOWN,11,1,10.0,charts_viral50,4QtiVmuA88tPQiCOHZuQ5b,NaN,NaN,0haZhu4fFKt0Ag94kZDiz2,NaN,NaN,NaN,Mexico,Person
43,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",21,2018-04-16,Sofía Reyes,Argentina,viral50,MOVE_DOWN,11,1,17.0,charts_viral50,4QtiVmuA88tPQiCOHZuQ5b,NaN,NaN,0haZhu4fFKt0Ag94kZDiz2,NaN,NaN,NaN,Mexico,Person
44,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",34,2018-04-23,Sofía Reyes,Argentina,viral50,MOVE_DOWN,11,1,21.0,charts_viral50,4QtiVmuA88tPQiCOHZuQ5b,NaN,NaN,0haZhu4fFKt0Ag94kZDiz2,NaN,NaN,NaN,Mexico,Person
45,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",33,2018-04-30,Sofía Reyes,Argentina,viral50,MOVE_DOWN,11,1,34.0,charts_viral50,4QtiVmuA88tPQiCOHZuQ5b,NaN,NaN,0haZhu4fFKt0Ag94kZDiz2,NaN,NaN,NaN,Mexico,Person
46,"1, 2, 3!",42,2018-07-23,SEUNGRI,Argentina,viral50,NEW_ENTRY,3,10,NaN,charts_viral50,3EyJd7XKw4lrIZXQboMDbv,205.304,False,20j1uz7iDOtIvIzCr5S8nx,"[""k-pop""]",1.0,2018-07-20,NaN,NaN
47,"1, 2, 3!",10,2018-07-30,SEUNGRI,Argentina,viral50,NEW_ENTRY,3,10,42.0,charts_viral50,3EyJd7XKw4lrIZXQboMDbv,NaN,NaN,20j1uz7iDOtIvIzCr5S8nx,NaN,NaN,NaN,NaN,NaN
48,"1, 2, 3!",27,2018-08-06,SEUNGRI,Argentina,viral50,MOVE_DOWN,3,10,10.0,charts_viral50,3EyJd7XKw4lrIZXQboMDbv,NaN,NaN,20j1uz7iDOtIvIzCr5S8nx,NaN,NaN,NaN,NaN,NaN
49,1-800-273-8255,20,2017-05-08,Logic,Argentina,viral50,MOVE_DOWN,3,17,NaN,charts_viral50,5tz69p7tJuGPeMGwNTxYuV,250.173,True,4xRYI6VqpkE3UwrDrAZL8L,[],3.0,2017-05-05,United States,Person

In [3]:
processed_data = ChartPreprocessor().transform(processed_data)

In [4]:
processed_data.head()

,track_name,rank,date,artist_name,region,chart_type,position_change,weeks_on_chart,peak_position,previous_rank,...,track_id,duration,explicit,artist_id,genres,artist_count,release_date,country,type,spotify_track_id
0,#BrooklynBloodPop!,7,2021-05-17,SyKo,Argentina,viral50,SAME_POSITION,9,5,NaN,...,5tDbyeaCvxjNCBcupQucGo,145.612,True,08ZqXO40nMrhBoGma4kls2,"[""hyperpop""]",1.0,2020-07-27,Seattle,Person,5tDbyeaCvxjNCBcupQucGo
1,#BrooklynBloodPop!,5,2021-05-24,SyKo,Argentina,viral50,MOVE_UP,9,5,7.0,...,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person,5tDbyeaCvxjNCBcupQucGo
2,#BrooklynBloodPop!,11,2021-05-31,SyKo,Argentina,viral50,MOVE_DOWN,9,5,5.0,...,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person,5tDbyeaCvxjNCBcupQucGo
3,#BrooklynBloodPop!,13,2021-06-07,SyKo,Argentina,viral50,MOVE_DOWN,9,5,11.0,...,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person,5tDbyeaCvxjNCBcupQucGo
4,#BrooklynBloodPop!,16,2021-06-14,SyKo,Argentina,viral50,MOVE_DOWN,9,5,13.0,...,5tDbyeaCvxjNCBcupQucGo,NaN,NaN,08ZqXO40nMrhBoGma4kls2,NaN,NaN,NaN,Seattle,Person,5tDbyeaCvxjNCBcupQucGo

In [5]:
date_dim_processor = DateDimension(processed_data, date_column='date')
dim_date = date_dim_processor.transform()

region_dim_processor = RegionDimension(processed_data, region_column='region')
dim_region = region_dim_processor.transform()


artist_dim_processor = ArtistDimension(processed_data)
dim_artist = artist_dim_processor.transform()

track_dim_processor = TrackDimension(processed_data)
dim_track = track_dim_processor.transform()

c:\Users\ulasz\OneDrive\Pulpit\studia\sem6\hurtownie danych\spotify-dwh\etl\transform\transform.py:195: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['explicit'] = df['explicit'].fillna(False).astype(bool)

In [6]:
dim_date

,date_id,year,month,day,day_of_week,quarter,season,week_of_year,is_holiday,is_weekend,date,holiday_name
0,1,2021,5,17,Monday,2,Spring,20,False,False,2021-05-17,None
1,2,2021,5,24,Monday,2,Spring,21,False,False,2021-05-24,None
2,3,2021,5,31,Monday,2,Spring,22,True,False,2021-05-31,Memorial Day
3,4,2021,6,7,Monday,2,Summer,23,False,False,2021-06-07,None
4,5,2021,6,14,Monday,2,Summer,24,False,False,2021-06-14,None
5,6,2021,6,21,Monday,2,Summer,25,False,False,2021-06-21,None
6,7,2021,6,28,Monday,2,Summer,26,False,False,2021-06-28,None
7,8,2021,7,5,Monday,3,Summer,27,True,False,2021-07-05,Independence Day (observed)
8,9,2021,7,12,Monday,3,Summer,28,False,False,2021-07-12,None
9,10,2018,1,8,Monday,1,Winter,2,False,False,2018-01-08,None
10,11,2018,1,15,Monday,1,Winter,3,True,False,2018-01-15,Martin Luther King Jr. Day
11,12,2018,1,22,Monday,1,Winter,4,False,False,2018-01-22,None
12,13,2020,6,8,Monday,2,Summer,24,False,False,2020-06-08,None
13,14,2020,7,13,Monday,3,Summer,29,False,False,2020-07-13,None
14,15,2020,11,2,Monday,4,Autumn,45,False,False,2020-11-02,None
15,16,2020,11,16,Monday,4,Autumn,47,False,False,2020-11-16,None
17,17,2018,5,7,Monday,2,Spring,19,False,False,2018-05-07,None
18,18,2018,9,24,Monday,3,Autumn,39,False,False,2018-09-24,None
19,19,2018,8,20,Monday,3,Summer,34,False,False,2018-08-20,None
20,20,2020,4,27,Monday,2,Spring,18,False,False,2020-04-27,None
21,21,2020,1,13,Monday,1,Winter,3,False,False,2020-01-13,None
22,22,2020,1,20,Monday,1,Winter,4,True,False,2020-01-20,Martin Luther King Jr. Day
23,23,2020,1,27,Monday,1,Winter,5,False,False,2020-01-27,None
24,24,2020,2,17,Monday,1,Winter,8,True,False,2020-02-17,Washington's Birthday
25,25,2020,2,24,Monday,1,Winter,9,False,False,2020-02-24,None
26,26,2020,3,2,Monday,1,Spring,10,False,False,2020-03-02,None
27,27,2020,3,9,Monday,1,Spring,11,False,False,2020-03-09,None
28,28,2017,9,4,Monday,3,Autumn,36,True,False,2017-09-04,Labor Day
29,29,2017,9,11,Monday,3,Autumn,37,False,False,2017-09-11,None
30,30,2017,1,2,Monday,1,Winter,1,True,False,2017-01-02,New Year's Day (observed)
32,31,2018,7,9,Monday,3,Summer,28,False,False,2018-07-09,None
35,32,2018,2,19,Monday,1,Winter,8,True,False,2018-02-19,Washington's Birthday
36,33,2018,2,26,Monday,1,Winter,9,False,False,2018-02-26,None
37,34,2018,3,5,Monday,1,Spring,10,False,False,2018-03-05,None
38,35,2018,3,12,Monday,1,Spring,11,False,False,2018-03-12,None
39,36,2018,3,19,Monday,1,Spring,12,False,False,2018-03-19,None
40,37,2018,3,26,Monday,1,Spring,13,False,False,2018-03-26,None
41,38,2018,4,2,Monday,2,Spring,14,False,False,2018-04-02,None
42,39,2018,4,9,Monday,2,Spring,15,False,False,2018-04-09,None
43,40,2018,4,16,Monday,2,Spring,16,False,False,2018-04-16,None
44,41,2018,4,23,Monday,2,Spring,17,False,False,2018-04-23,None
45,42,2018,4,30,Monday,2,Spring,18,False,False,2018-04-30,None
46,43,2018,7,23,Monday,3,Summer,30,False,False,2018-07-23,None
47,44,2018,7,30,Monday,3,Summer,31,False,False,2018-07-30,None
48,45,2018,8,6,Monday,3,Summer,32,False,False,2018-08-06,None
49,46,2017,5,8,Monday,2,Spring,19,False,False,2017-05-08,None

In [7]:
dim_region

,region_id,region_name,region_code,region_population,region_language,region_continent
0,1,Argentina,ARG,45538401,Spanish,South America

In [8]:
dim_artist

,artist_id,artist_spotify_id,artist_name,artist_genre,artist_country,artist_type
0,1,08ZqXO40nMrhBoGma4kls2,SyKo,hyperpop,Seattle,Person
9,2,7K9rdoOJSiKXoVXPlSkGKT,Paty Cantú,latin pop,Mexico,Person
12,3,5iB9AOsC0IyhPYES06AYo0,BMW Kenny,Unknown,Unknown,Person
13,4,2qWK8K2Jfh67UqtwY8tCW6,YSY A,argentine trap,Argentina,Person
17,5,2AfmfGFbe0A0WsTYm0SDTx,i-dle,k-pop,South Korea,Group
18,6,4bXUaTjc7TQTvLqqCAlfYt,Jack Back,tech house,United States,Person
19,7,7nwUJBm0HE4ZxD3f5cy5ok,Aretha Franklin,soul,United States,Person
20,8,2sSqkk6j5gRa7MzeQqMfIN,Covi Quintana,Unknown,Unknown,Person
21,9,7eLcDZDYHXZCebtQmVFL25,Aitana,Unknown,Spain,Person
28,10,06HL4z0CvFAxyc27GXpf02,Taylor Swift,Unknown,United States,Person
30,11,01nUdqwuIHCHLZNP2TvYVF,Boy Wonder CF,reggaeton,Unknown,Unknown
31,12,6EVyI0S0b1Ld2nm37m5x85,Raffaella Carrà,Unknown,Italy,Person
32,13,68nJ4J8L6X6HZNTuZ9e7yT,SACRE,nu disco,Unknown,Person
33,14,0ghlgldX5Dd6720Q3qFyQB,TOMORROW X TOGETHER,k-pop,South Korea,Group
35,15,0haZhu4fFKt0Ag94kZDiz2,Sofía Reyes,latin pop,Mexico,Person
46,16,20j1uz7iDOtIvIzCr5S8nx,SEUNGRI,k-pop,Unknown,Unknown
49,17,4xRYI6VqpkE3UwrDrAZL8L,Logic,Unknown,United States,Person

In [9]:
dim_track

,track_id,track_name,artist_name,artist_count,duration,explicit,spotify_track_id,release_date
0,1,#BrooklynBloodPop!,SyKo,1,145.612,True,5tDbyeaCvxjNCBcupQucGo,2020-07-27
9,2,#Natural,Paty Cantú,2,227.266,False,3y7XIu4NloDcCSekDbCvf6,2018-05-25
12,3,#WIPEITDOWN (TikTok Classics Version),BMW Kenny,2,135.317,False,5qOE3kEU14vcc6OUDkgKkv,2022-08-12
13,4,#Ysya2020 Vol. 1 - Una de Dos,YSY A,2,116.599,False,7nFta4LZyL0MTDDqbjiQW2,2020-06-22
14,5,#Ysya2020 Vol. 4 - Pasa Que Yo,YSY A,2,100.365,False,7qf15ZBTnAyOZX5UIWrsKj,2020-10-11
15,6,#Ysya2020 Vol. 5 - Silbando,YSY A,2,119.438,False,6TI490muJ6RgFsYJc626BZ,2020-10-18
16,7,#Ysya2020 Vol. 6 - Un Flow de Infarto,YSY A,2,142.376,False,2byu6eeLWaBq88ZtusqU4V,2020-10-26
17,8,Good Thing,i-dle,1,154.386,False,6d8DgvFxp6lbdfOw9BVkLS,2025-05-19
18,9,(It Happens) Sometimes,Jack Back,1,202.276,False,4psxV3oAIDBXKL2oS9KcFq,2018-08-31
19,10,(You Make Me Feel Like) A Natural Woman,Aretha Franklin,1,165.333,False,5K09WxKdlkroDyEVyOSySy,1968-01-22
20,11,(no me despegues tu boca),Covi Quintana,1,220.840,False,2j0KnNhlO9lY1EWPOkblK3,2021-05-21
21,12,+ (MÁS),Aitana,2,219.354,False,1MXzojJav1N4cREWTFm1iZ,2020-12-10
28,13,...Ready For It?,Taylor Swift,1,208.186,False,2yLa0QULdQr0qAIvVwN6B5,2017-11-10
30,14,"0 Sentimientos (Remix) [feat. Baby Rasta, Dark...",Boy Wonder CF,8,335.736,False,3gYco8uoFBmpxqYlz3Zhs7,2023-11-21
31,15,0303456 - 1999 vrs,Raffaella Carrà,1,199.920,False,1TtHlaxGzDhyF2GyX8dqWV,1999-10-29
32,16,06:00AM CHILDREN OF THE SUN,SACRE,1,225.693,False,5BLWG0gtrci22tCyPu2bsP,2020-07-10
33,17,0X1=LOVESONG (I Know I Love You) feat. Seori,TOMORROW X TOGETHER,2,202.203,False,1Z8TPHiKeCUyClxV6WTTIf,2021-05-31
35,18,"1, 2, 3 (feat. Jason Derulo & De La Ghetto)",Sofía Reyes,3,201.526,False,4QtiVmuA88tPQiCOHZuQ5b,2018-02-16
46,19,"1, 2, 3!",SEUNGRI,1,205.304,False,3EyJd7XKw4lrIZXQboMDbv,2018-07-20
49,20,1-800-273-8255,Logic,3,250.173,True,5tz69p7tJuGPeMGwNTxYuV,2017-05-05

In [10]:
fact_chart = FactChart(processed_data, dim_track, dim_artist, dim_date, dim_region)
fact_df = fact_chart.transform()

Kolumny po merge z dim_track: ['track_name_x', 'rank', 'date', 'artist_name_x', 'region', 'chart_type', 'position_change', 'weeks_on_chart', 'peak_position', 'previous_rank', 'source_type', 'track_id_x', 'duration', 'explicit', 'artist_id_x', 'genres', 'artist_count', 'release_date_x', 'country', 'type', 'spotify_track_id_x', 'spotify_track_id_y', 'track_name_y', 'artist_name_y', 'release_date_y', 'track_key', 'artist_id_y', 'artist_spotify_id', 'chart_date', 'date_key', 'region_key', 'region_name']
Kolumny w df przed zwróceniem: ['track_name_x', 'rank', 'date', 'artist_name_x', 'region', 'chart_type', 'position_change', 'weeks_on_chart', 'peak_position', 'previous_rank', 'source_type', 'track_id_x', 'duration', 'explicit', 'artist_id_x', 'genres', 'artist_count', 'release_date_x', 'country', 'type', 'spotify_track_id_x', 'spotify_track_id_y', 'track_name_y', 'artist_name_y', 'release_date_y', 'track_key', 'artist_id_y', 'artist_spotify_id', 'chart_date', 'date_key', 'region_key', 'region_name', 'release_date', 'days_since_release', 'weeks_since_release', 'months_since_release', 'chart_id']

In [11]:
fact_df

,chart_id,track_key,artist_key,date_key,region_key,source_type,chart_type,rank,weeks_on_chart,peak_position,position_change,chart_date,release_date,days_since_release,weeks_since_release,months_since_release
0,1,1,1,1,1,charts_viral50,viral50,7,9,5,-7,2021-05-17,2020-07-27,294,42,10
1,2,1,1,2,1,charts_viral50,viral50,5,9,5,2,2021-05-24,2020-07-27,301,43,10
2,3,1,1,3,1,charts_viral50,viral50,11,9,5,-6,2021-05-31,2020-07-27,308,44,10
3,4,1,1,4,1,charts_viral50,viral50,13,9,5,-2,2021-06-07,2020-07-27,315,45,11
4,5,1,1,5,1,charts_viral50,viral50,16,9,5,-3,2021-06-14,2020-07-27,322,46,11
5,6,1,1,6,1,charts_viral50,viral50,18,9,5,-2,2021-06-21,2020-07-27,329,47,11
6,7,1,1,7,1,charts_viral50,viral50,39,9,5,-21,2021-06-28,2020-07-27,336,48,11
7,8,1,1,8,1,charts_viral50,viral50,36,9,5,3,2021-07-05,2020-07-27,343,49,12
8,9,1,1,9,1,charts_viral50,viral50,46,9,5,-10,2021-07-12,2020-07-27,350,50,12
9,10,2,2,10,1,charts_viral50,viral50,22,3,12,-22,2018-01-08,2018-05-25,-137,-20,-4
10,11,2,2,11,1,charts_viral50,viral50,12,3,12,10,2018-01-15,2018-05-25,-130,-19,-4
11,12,2,2,12,1,charts_viral50,viral50,27,3,12,-15,2018-01-22,2018-05-25,-123,-18,-4
12,13,3,3,13,1,charts_viral50,viral50,43,1,43,-43,2020-06-08,2022-08-12,-795,-114,-26
13,14,4,4,14,1,charts_viral50,viral50,32,1,32,-32,2020-07-13,2020-06-22,21,3,1
14,15,5,4,15,1,charts_viral50,viral50,28,1,28,-28,2020-11-02,2020-10-11,22,3,1
15,16,6,4,16,1,charts_viral50,viral50,43,1,43,-43,2020-11-16,2020-10-18,29,4,1
16,17,7,4,16,1,charts_viral50,viral50,22,1,22,-22,2020-11-16,2020-10-26,21,3,1
17,18,8,5,17,1,charts_viral50,viral50,42,1,42,-42,2018-05-07,2025-05-19,-2569,-367,-84
18,19,9,6,18,1,charts_viral50,viral50,25,1,25,-25,2018-09-24,2018-08-31,24,3,1
19,20,10,7,19,1,charts_viral50,viral50,31,1,31,-31,2018-08-20,1968-01-22,18473,2639,607
20,21,11,8,20,1,charts_viral50,viral50,49,1,49,-49,2020-04-27,2021-05-21,-389,-56,-13
21,22,12,9,21,1,charts_viral50,viral50,25,7,25,-25,2020-01-13,2020-12-10,-332,-48,-11
22,23,12,9,22,1,charts_viral50,viral50,25,7,25,0,2020-01-20,2020-12-10,-325,-47,-11
23,24,12,9,23,1,charts_viral50,viral50,44,7,25,-19,2020-01-27,2020-12-10,-318,-46,-11
24,25,12,9,24,1,charts_viral50,viral50,46,7,25,-2,2020-02-17,2020-12-10,-297,-43,-10
25,26,12,9,25,1,charts_viral50,viral50,42,7,25,4,2020-02-24,2020-12-10,-290,-42,-10
26,27,12,9,26,1,charts_viral50,viral50,50,7,25,-8,2020-03-02,2020-12-10,-283,-41,-9
27,28,12,9,27,1,charts_viral50,viral50,49,7,25,1,2020-03-09,2020-12-10,-276,-40,-9
28,29,13,10,28,1,charts_viral50,viral50,1,2,1,-1,2017-09-04,2017-11-10,-67,-10,-2
29,30,13,10,29,1,charts_viral50,viral50,10,2,1,-9,2017-09-11,2017-11-10,-60,-9,-2
30,31,14,11,30,1,charts_viral50,viral50,7,1,7,-7,2017-01-02,2023-11-21,-2514,-360,-82
31,32,15,12,9,1,charts_viral50,viral50,36,1,36,-36,2021-07-12,1999-10-29,7927,1132,261
32,33,16,13,31,1,charts_viral50,viral50,49,1,49,-49,2018-07-09,2020-07-10,-732,-105,-24
33,34,17,14,7,1,charts_viral50,viral50,27,1,27,-27,2021-06-28,2021-05-31,28,4,1
34,35,17,14,6,1,charts_viral50,viral50,26,1,26,-26,2021-06-21,2021-05-31,21,3,1
35,36,18,15,32,1,charts_viral50,viral50,3,11,1,-3,2018-02-19,2018-02-16,3,0,0
36,37,18,15,33,1,charts_viral50,viral50,1,11,1,2,2018-02-26,2018-02-16,10,1,0
37,38,18,15,34,1,charts_viral50,viral50,9,11,1,-8,2018-03-05,2018-02-16,17,2,1
38,39,18,15,35,1,charts_viral50,viral50,15,11,1,-6,2018-03-12,2018-02-16,24,3,1
39,40,18,15,36,1,charts_viral50,viral50,16,11,1,-1,2018-03-19,2018-02-16,31,4,1
40,41,18,15,37,1,charts_viral50,viral50,16,11,1,0,2018-03-26,2018-02-16,38,5,1
41,42,18,15,38,1,charts_viral50,viral50,10,11,1,6,2018-04-02,2018-02-16,45,6,2
42,43,18,15,39,1,charts_viral50,viral50,17,11,1,-7,2018-04-09,2018-02-16,52,7,2
43,44,18,15,40,1,charts_viral50,viral50,21,11,1,-4,2018-04-16,2018-02-16,59,8,2
44,45,18,15,41,1,charts_viral50,viral50,34,11,1,-13,2018-04-23,2018-02-16,66,9,2
45,46,18,15,42,1,charts_viral50,viral50,33,11,1,1,2018-04-30,2018-02-16,73,10,2
46,47,19,16,43,1,charts_viral50,viral50,42,3,10,-42,2018-07-23,2018-07-20,3,0,0
47,48,19,16,44,1,charts_viral50,viral50,10,3,10,32,2018-07-30,2018-07-20,10,1,0
48,49,19,16,45,1,charts_viral50,viral50,27,3,10,-17,2018-08-06,2018-07-20,17,2,1
49,50,20,17,46,1,charts_viral50,viral50,20,3,17,-20,2017-05-08,2017-05-05,3,0,0

In [12]:
processed_data2 = ChartPreprocessor().transform(processed_data2)

NameError: name 'processed_data2' is not defined

In [ ]:
date_dim_processor = DateDimension(processed_data2, date_column='date')
dim_date = date_dim_processor.transform()

region_dim_processor = RegionDimension(processed_data2, region_column='region')
dim_region = region_dim_processor.transform()


artist_dim_processor = ArtistDimension(processed_data2)
dim_artist = artist_dim_processor.transform()

track_dim_processor = TrackDimension(processed_data2)
dim_track = track_dim_processor.transform()

In [ ]:
dim_date

,date_id,year,month,day,day_of_week,quarter,season,week_of_year,is_holiday,is_weekend,date,holiday_name
0,1,2013,1,23,Wednesday,1,Winter,4,False,False,2013-01-23,None

In [ ]:
dim_region

,region_id,region_name,region_code,region_population,region_language,region_continent
0,1,Global,WLD,8061876001,English,Global

In [ ]:
dim_track

Empty DataFrame
Columns: []
Index: []

In [ ]:
dim_artist

Empty DataFrame
Columns: []
Index: []

In [ ]:
fact_chart = FactChart(processed_data2, dim_track, dim_artist, dim_date, dim_region)
fact_df = fact_chart.transform()

KeyError: "None of [Index(['track_id', 'track_name', 'artist_name', 'release_date'], dtype='object')] are in the [columns]"